### ISSUE TITLE
Mod fails to load Correctly

### ISSUE THREAD

**Issue by Jokers-Wyld** [TBoshoven/MinecraftMods#109]
I attempt to load the game with the mod and i get a error report, info attached

![image_2022-07-13_081647307](https://user-images.githubusercontent.com/97351009/178731330-78ad00ea-e918-4c85-8e07-4368c7a2f97a.png)
[crash-2022-07-13_08.15.35-fml.txt](https://github.com/TBoshoven/MinecraftMods/files/9101988/crash-2022-07-13_08.15.35-fml.txt)

**Comment by TBoshoven** [comment]
While I don't directly recognize the error, I suspect the problem is what was reported in #108: I never made a version for 1.18.2 .
Since it looks like you loaded the 1.18 (Minecraft's equivalent of "1.18.0") version in 1.18.2, I suspect things broke.

I'll put a 1.18.2 version out in a few minutes.
Please try it out and report back if it solves the issue :)

**Comment by Jokers-Wyld** [comment]
thanks ill try it

**Comment by Jokers-Wyld** [comment]
Everything is working fine now Thanks for the help
